### ISSUE TITLE
Problem configuring docker_proxy settings

### ISSUE THREAD

**Issue by TimVerboisCgk** [ansible-ThoTeam/nexus3-oss#371] opened 2023-02-16 13:15 UTC
When I configure a proxy as is defined by default:

```
    nexus_config_docker: true
    nexus_docker_proxy_port: 18079
    nexus_repos_docker_proxy:
    - name: docker-proxy
       http_port: "{{ nexus_docker_proxy_port }}"
       v1_enabled: True
       index_type: "HUB"
       remote_url: "https://registry-1.docker.io"
       use_nexus_certificates_to_access_index: false
```

I get the following error:

```
    "msg": "failed to combine variables, expected dicts but got a 'str' and a 'dict': \n\"N\"\n{\"format\": \"docker\", \"type\": \"proxy\"}"
```

This comes from the fact that processing the dict `nexus_repos_docker_proxy` in this step:

```
    - name: apply defaults to docker proxy repos
      set_fact:
        nexus_repos_docker_proxy: >-
          {%- set result=[] -%}
          {%- for repo in nexus_repos_docker_proxy -%}
            {{ result.append(_nexus_repos_docker_defaults | combine(repo)) }}
          {%- endfor -%}
          {{ result | to_json | from_json }}
```

results in this filled in fact:

```
    "ansible_facts": {
        "nexus_repos_docker_proxy": "None[{'blob_store': 'default', 'force_basic_auth': True, 'strict_content_validation': True, 'version_policy': 'release', 'layout_policy': 'strict', 'write_policy': 'allow_once', 'maximum_component_age': 1440, 'maximum_metadata_age': 1440, 'negative_cache_enabled': True, 'negative_cache_ttl': 1440, 'cache_foreign_layers': False, 'foreign_layer_url_whitelist': [], 'name': 'docker-proxy', 'http_port': 18079, 'v1_enabled': True, 'index_type': 'HUB', 'remote_url': 'https://registry-1.docker.io', 'use_nexus_certificates_to_access_index': False}]"
    },
    "changed": false
}
```

You can see that this results in a String starting with "None".  I cannot quite figure out why it adds a None to this, but this looks like a bug to me.

I'm using the latest versions of Nexus and of this role

**Comment by zeitounator** [comment] 2023-02-16 17:14
Did you override the `_nexus_repos_docker_defaults` variable from defaults? If yes make sure it is a dict. Note that your example variable definition contains indentation errors so it's hard to be sure where this error comes from exactly.

This role is used daily by my colleagues for a nexus install containing 500+ repos. Applying defaults to each repo definition is done the exact same way for all repos (i.e. combining the defaults with each repo). Our install contains more than a hundred docker registries from which a dozen are proxies. This has been working flawlessly for approximately the last 4 years. So I'm quite positive that the problem is in your data and might be in a place you're not showing above.

**Comment by zeitounator** [comment] 2023-03-26 16:35
Closing this support ticket as there was no other return.

**Closed by zeitounator** 2023-03-26 16:35 UTC

**Comment by EBCEEB** [comment] 2023-09-14 11:31
Faced the same issue.

Googled this: (see discussion on the first answer):

https://stackoverflow.com/questions/49619445/how-to-append-to-a-list-in-jinja2-for-ansible

> The cleaner solution to avoid printing anything is to use {% do server_ip.append(ip+":"+port) %}

**Comment by EBCEEB** [comment] 2023-09-14 11:48
> The cleaner solution to avoid printing anything is to use {% do server_ip.append(ip+":"+port) %}

Checked this solution - it requires Jinja extension.

Did with `or ""`

**Comment by EBCEEB** [comment] 2023-09-14 11:52
Found one more place to fix - "apply defaults to privileges"
