### ISSUE TITLE
Provisioning fails on Debain when using nexus3-oss role with Packer

### ISSUE THREAD

**Issue by nishant009** [ansible-ThoTeam/nexus3-oss#136] opened 2019-01-17 16:19 UTC
Hello,

I am getting an error running the `nexus3-oss` role. I am trying to install `nexus` repository on an `EC2` instance provisioned using `packer`.

#### Error Details
The error I'm getting is coming from the invocation of [this](https://github.com/ansible-ThoTeam/nexus3-oss/blob/7c2c39987b865378933fb54220a02ee451254066/tasks/declare_script_each.yml#L2) task that is part of the `nexus3-oss` role. Below is the dump of error output:
```
amazon-ebs: TASK [ansible-ThoTeam.nexus3-oss : Removing (potential) previously declared Groovy script create_repo_yum_proxy] ***
amazon-ebs: fatal: [default]: FAILED! => {"msg": "failed to resolve remote temporary directory from ansible-tmp-1547681805.35-1997090464384: `( umask 77 && mkdir -p \"` echo /home/admin/.ansible/tmp/ansible-tmp-1547681805.35-1997090464384 `\" && echo ansible-tmp-1547681805.35-1997090464384=\"` echo /home/admin/.ansible/tmp/ansible-tmp-1547681805.35-1997090464384 `\" )` returned empty string"}
amazon-ebs: 	to retry, use: --limit @/home/ubuntu/platformation/ansible/nexus.retry
amazon-ebs:
amazon-ebs: PLAY RECAP *********************************************************************
amazon-ebs: default                    : ok=155  changed=22   unreachable=0    failed=
```
I want to note that this is not the first time the task in question is invoked during the installation process and the previous calls have succeed before the failure happens. Rerunning installation causes the failure to happen at a different invocation of the same task.

#### System Details
I have `Ubuntu 18.04.1 LTS (Bionic Beaver)` on my machine (host) that is running `Ansible V2.7.5` and `Packer V0.12.0`. The provisioned `EC2` instance (remote) on which `nexus` is being installed has `Debian GNU/Linux 9 (stretch)` as its OS.

#### Code
Here is a link to my [nexus](https://gist.github.com/nishant009/86cb1558916ff5850e9020ca47fcc9c8) playbook as well as a link to my [packer](https://gist.github.com/nishant009/cb6a9e143fb76fd277943ed3425465cb) file.

**Comment by zeitounator** [comment] 2019-02-09 12:03
I have absolutely no clue of the problem and I will not be able to reproduce it. This is a very low level ansible error. The task fails as ansible is creating a temporary folder to upload the python script it will then run to execute the task on the remote (because either the umask or the mkdir command failed). You have to check what is happening preciselly on you ec2 instance.

**Comment by zeitounator** [comment] 2019-02-21 16:50
@nishant009 Where you able to check what's going on ?

**Comment by zeitounator** [comment] 2019-03-22 14:04
Closing since I didn't get any update. Feel free to reopen if needed.

**Closed by zeitounator** 2019-03-22 14:04 UTC
Labels: Support, Waiting
