### ISSUE TITLE
Role fails when creating content selector

### ISSUE THREAD

**Issue by evgeniy-pupkov** [ansible-ThoTeam/nexus3-oss#242] opened 2020-02-11 11:41 UTC
Hello! 
I'm getting a groovy script exception on content selector creation step. 
Here's listing of verbose output
```json
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {
    "changed": false,
    "connection": "close",
    "content": "{\n  \"name\" : \"create_content_selector\",\n  \"result\" : \"javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: org.sonatype.nexus.internal.selector.SelectorManagerImpl$$EnhancerByGuice$$a85e5f3d.newSelectorConfiguration() is applicable for argument types: () values: []\"\n}",
    "content_length": "305",
    "content_type": "application/json",
    "date": "Tue, 11 Feb 2020 10:58:39 GMT",
    "elapsed": 0,
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": "{\"search_expression\": \"format==\\\"docker\\\" and path=~\\\"/v2/\\\"\", \"name\": \"docker-login\", \"description\": \"Selector for docker login privilege\"}",
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": true,
            "group": null,
            "headers": {
                "Content-Type": "text/plain"
            },
            "http_agent": "ansible-httpget",
            "method": "POST",
            "mode": null,
            "owner": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                200
            ],
            "timeout": 30,
            "unix_socket": null,
            "unsafe_writes": null,
            "url": "http://localhost:8081/service/rest/v1/script/create_content_selector/run",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "admin",
            "use_proxy": true,
            "user": "admin",
            "validate_certs": false
        }
    },
    "json": {
        "name": "create_content_selector",
        "result": "javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: org.sonatype.nexus.internal.selector.SelectorManagerImpl$$EnhancerByGuice$$a85e5f3d.newSelectorConfiguration() is applicable for argument types: () values: []"
    },
    "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request",
    "redirected": false,
    "server": "Nexus/3.19.1-01 (OSS)",
    "status": 400,
    "url": "http://localhost:8081/service/rest/v1/script/create_content_selector/run",
    "x_content_type_options": "nosniff"
}
```

I've taken content selector creation settings from examples in readme.
```
nexus_content_selectors:
  - name: docker-login
    description: Selector for docker login privilege
    search_expression: format=="docker" and path=~"/v2/"
```

**Comment by zeitounator** [comment] 2020-02-13 07:44
Hi @evgeniy-pupkov, can you please confirm your are using either the latest version ([v2.4.8](https://github.com/ansible-ThoTeam/nexus3-oss/releases/tag/v2.4.8)) or the master ?

**Comment by evgeniy-pupkov** [comment] 2020-02-13 09:34
It's master. Here's block from requirements file:
```yaml
- name: nexus3-oss
  src: git@github.com:ansible-ThoTeam/nexus3-oss.git
  scm: git
```

**Comment by zeitounator** [comment] 2020-02-14 14:37
I cannot reproduce your problem. Which version of nexus are your running ? If it is not the lastest, can you consider upgrading ?

I suspect this could be a groovy script registration problem. I suggest you run your playbook with `-e nexus_force_groovy_scripts_registration=true` and let me know if it fixes the problem. Else I will try to make further testing once I know your exact nexus version.

**Comment by zeitounator** [comment] 2020-02-20 17:31
@evgeniy-pupkov I actually hit the same issue with an older version of nexus: fix on the launchpad.

**Comment by zeitounator** [comment] 2020-02-20 17:34
Note that this will be merged without CI which si currently failing because of latest nexus version 3.21 and latest molecule version 3.0. Fixes underway as well. It will work with nexus version up to 3.20.

**Closed** 2020-02-20 17:35 UTC
Labels: Support

**Comment by zeitounator** [comment] 2020-02-21 15:49
Sorry @evgeniy-pupkov but I actually have to revert the "fix". I didn't see it at first because or the broken CI but it made the script fail again for version 3.20 and up. If you are deploying nexus < 3.20 you will have to stick to version 2.4.7.

**Comment by zeitounator** [comment] 2020-02-23 21:33
@evgeniy-pupkov I was finally able to work out a backward compatibility. This has been added in #247  and will be released in the next minutes. Meanwhile, be aware that retro-compat is very restricted and that e.g. cleanup policies and ldap config will not work with nexus < 3.20. Hope this helps.
